name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name : Checkout depot
          uses: actions/checkout@v4

        - name: Set up Java 21 with Corretto
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'corretto' 
        
        - name: Package with maven
        run: mvn –B package



      
