name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build java
    runs-on: ubuntu-latest
    steps:
      - name : Checkout depot
        uses: actions/checkout@v4

      - name: Set up Java 21 with Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto' 

      - name: Package with maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')

      - name: Mise en cache de maven
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: mise en case de SonarCloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonar-




      
