name: Java CI with Maven - Test and package

on: [push]

jobs:
    Salutations: # Nom du job : Salutations
        name: Salutations
        runs-on: ubuntu-latest # OS où s'exécute le job
        steps:
        - name: Hello #une tâche pour saluer
            env:
                personneASaluer: 'Mon voisin Totoro'
        run: echo "Bonjour ${personneASaluer}"
